#!/bin/sh

# Copyright (c) by Oliver Falk <oliver@linux-kernel.at>, 2012-2014

HOSTNAME=$1

if [ -z $HOSTNAME ]; then
	echo "No hostname given";
	exit -1
fi

TMP_FILE=/tmp/chk_csync2.$$.$HOSTNAME.dat

rm -f ${TMP_FILE}

ssh -oConnectTimeout=3 -oNumberOfPasswordPrompts=0 -oPasswordAuthentication=no -oStrictHostKeyChecking=no root@"$HOSTNAME" which csync2 >/dev/null 2>&1
if [ ! $? -eq 0 ]; then
	echo "OK: No csync2 installed | changes=0" 
	exit 0
fi

ssh -oConnectTimeout=3 -oNumberOfPasswordPrompts=0 -oPasswordAuthentication=no -oStrictHostKeyChecking=no root@"$HOSTNAME" csync2 -xvd > ${TMP_FILE} 2> /dev/null
exitcode=$?

if [ $exitcode == 255 ]; then
        echo "SSH exited with non zero exit code: $op";
        exit 1
fi

if [ -s ${TMP_FILE} ] ; then
	echo -e "WARNING: Changes found:\n`cat $TMP_FILE` | changes=`cat $TMP_FILE|wc -l`"
	exit 1
else
	echo "OK: No changes found | changes=0" 
	exit 0
fi

rm -f ${TMP_FILE}
